[project]
name = "server"
version = "0.0.1"
description = "FastAPI Server Starter"
readme = "README.md"
requires-python = "==3.14.2"
dependencies = [
    "fastapi==0.128.0",
    "gunicorn==23.0.0",
    "pydantic==2.12.5",
    "uvicorn==0.40.0",
]
